### ISSUE TITLE
Warning: Couldn't open libvulkan.so.1

### ISSUE THREAD

**Issue by markus-wa** [James226/webgpu-electron#1]
Hi, when running `npm run start` I get `Warning: Couldn't open libvulkan.so.1`

Do you know how to fix this?

I'm on Ubuntu 20.04 and have the `vulkan-sdk` installed

`libvulkan.so.1` seems to be available, just not found.

```
$ fd libvulkan.so.1 /usr
/usr/share/code/libvulkan.so.1
/usr/lib/slack/libvulkan.so.1
/usr/lib/i386-linux-gnu/libvulkan.so.1.2.170
/usr/lib/i386-linux-gnu/libvulkan.so.1
/usr/lib/x86_64-linux-gnu/libvulkan.so.1.2.170
/usr/lib/x86_64-linux-gnu/libvulkan.so.1
```

**Comment by giraphics** [comment]
Are you using electron nightly build?

Secondly, you have pass run time flags to electron.
 `electron --enable-unsafe-webgpu --enable-features=Vulkan .`

**Comment by markus-wa** [comment]
@giraphics you are a hero! I was aware of the first flag but was missing `--enable-features=Vulkan`

❤️
